version: '3.3'
services:
  auth:
    image: postgres:14.7
    container_name: auth_service
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: auth
    ports:
      - '5333:5432'
    volumes:
      - /tmp/auth_data:/var/lib/postgresql/data